on:
  workflow_call:
    secrets:
      VKCS_PASSWORD:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo "Testing"
